User followers
Fiu-Fit/users-service pull request #38
Opened 2023-05-21 23:38 UTC by rplatini

2023-05-22 00:08 UTC, ianshih2003 requested changes

2023-05-22 00:08 UTC, ianshih2003 commented on prisma/schema.prisma
> +  followingId Int   @map("following_id")
fijate como declarar foreign keys https://www.prisma.io/docs/concepts/components/prisma-schema/relations

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +        followingId: followerId,
Es raro que `followingId: followerId` cuando existe una field followerId, hablemos con @ManuSanchez02 los nombres

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +    });
Se puede hacer mas optimo (leer: https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries)

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/user/user.controller.ts
> +  }
Lo moveria a su propio controller, que en vez de params sean query params

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +  }
Parece que no se usa esto

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +  async getUserFollowings(id: number): Promise<Page<User>> {
podes renombrar el parametro a followerId para hacer `{ where: { followerId } }`

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +      }),
Para que usas esto?

2023-05-22 00:08 UTC, ianshih2003 commented on src/modules/followers/follower.service.ts
> +      }),
Para que usas esto?

2023-05-22 13:07 UTC, rplatini commented on src/modules/user/user.controller.ts
> +  }
Dale. Pero una pregunta, yo lo habia pensado asi para que los endpoints quedaran de la forma: `URL/users/{id}/follow` por ejemplo, onda que pertenezcan a los endpoints de los usuarios. Si hago un controller nuevo los endpoints serian asi: `URL/follow` y los ids con querys?

2023-05-23 17:50 UTC, ianshih2003 approved these changes

2023-05-23 17:50 UTC, merged